kind: pipeline
type: docker

name: drone-server-build

steps:
  - name: build
    image: docker:latest
    environment:
      DOMAIN_URL:
        from_secret: DOMAIN_URL
      ADMIN_EMAIL:
        from_secret: ADMIN_EMAIL
      VIDEO_HASH:
        from_secret: VIDEO_HASH
    commands:
      - docker compose build nextjs-app
    when:
      branch:
        - dev
  
  # - name: publish
  #   image: plugins/docker
  #   settings:
  #     repo: your-docker-registry/your-docker-image-name
  #     tags: [your-tag, latest]
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
