kind: pipeline
type: docker

name: drone-server-build

steps:
  - name: build
    image: docker:latest
    commands:
      - docker compose build nextjs-app
  
  # - name: publish
  #   image: plugins/docker
  #   settings:
  #     repo: your-docker-registry/your-docker-image-name
  #     tags: [your-tag, latest]
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
