kind: pipeline
type: docker
name: MegaLinter

workspace:
  path: /tmp/lint

steps:

- name: megalinter
  image: oxsecurity/megalinter:v7
  environment:
    DEFAULT_WORKSPACE: /tmp/lint
    ENABLE: JAVASCRIPT,YAML,MARKDOWN

trigger:
  event:
    include:
      - push
      - pull_request

---

kind: pipeline
type: docker
name: DockerTestBuild

steps:
  - name: build
    image: docker:latest
    environment:
      DOMAIN_URL:
        from_secret: DOMAIN_URL
      ADMIN_EMAIL:
        from_secret: ADMIN_EMAIL
      VIDEO_HASH:
        from_secret: VIDEO_HASH
    commands:
      - docker compose build nextjs-app -t test-build-${DRONE_BUILD_NUMBER}

  - name: test
    image: test-build-${DRONE_BUILD_NUMBER}
    commands:
      - npm run test

trigger:
  event:
    include:
      - push
      - pull_request

---

kind: pipeline
type: docker
name: DeployProduction

steps:
  - name: build
    image: docker:latest
    environment:
      DOMAIN_URL:
        from_secret: DOMAIN_URL
      ADMIN_EMAIL:
        from_secret: ADMIN_EMAIL
      VIDEO_HASH:
        from_secret: VIDEO_HASH
    commands:
      - docker compose build nextjs-app --tag prod-build-${DRONE_BUILD_NUMBER}
  
  - name: publish
    image: plugins/docker
    settings:
      repo: ${private_registry}/nextjs-app
      tags: ["prod-build-${DRONE_BUILD_NUMBER}", latest]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  target:
    - production
  event:
    - promote