version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    hostname: haproxy
    env_file: ./.env
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - certificates:/usr/local/etc/haproxy/certificates:ro
    networks:
      - default
      - hapnet
    ports:
      - "80:80"
      - "443:443"
      - "4001:4001" # ipfs switch
      - "9097:9097" # ipfs pinning svc
      - "9999"
  certbot:
    container_name: certbot
    build: 
      context: ./certbot
      args:
        - DO_TOKEN=${DIGITALOCEAN_TOKEN}
    hostname: certbot
    env_file: ./.env
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do . /etc/scripts/renew-certificates.sh ; sleep 12h & wait $${!}; done;'"
    restart: always
    volumes:
      - certificates:/etc/certificates
    networks:
      - default
      - hapnet
    ports:
      - "380:380"
    secrets:
      - digitalocean_token
  nextjs-app:
    build: ./nextjs-docker
    container_name: nextjs-app
    hostname: nextjs
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - hapnet

networks:
  hapnet:
    name: hapnet
    driver: bridge
    internal: true

volumes:
  certificates:

secrets:
  digitalocean_token:
    file: ./digitalocean.ini