version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    hostname: haproxy
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - certificates:/usr/local/etc/haproxy/certificates:ro
    networks:
      - default
      - hapnet
    ports:
      - "80:80"
      - "443:443"
      - "9999"
  certbot:
    build: ./certbot
    image: certbot/certbot:latest
    container_name: certbot
    hostname: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do . /etc/scripts/renew-certificates.sh ; sleep 12h & wait $${!}; done;'"
    restart: always
    volumes:
      - certificates:/etc/certificates
    networks:
      - default
      - hapnet
    ports:
      - "380:380"
  nextjs-app:
    build: ./nextjs-docker
    container_name: nextjs-app
    hostname: nextjs
    restart: unless-stopped
    env_file: ./.env
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - hapnet

networks:
  hapnet:
    name: hapnet
    driver: bridge
    internal: true
