version: "3.8"

services:
  website:
    build: ./nextjs-docker
    container_name: website
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
