# version: 2.1
# orbs:
#   discord: antonioned/discord@0.1.0

jobs:
  check-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git clone -b staging "$CIRCLE_REPOSITORY_URL" .
      - run: |
          if [ << pipeline.git.revision >> == $(git rev-parse HEAD) ]; then
            echo "SUCCESS: deploy conditions met"
            exit 0
          else
            echo "ERROR: You can only deploy when main and staging point to the same commit."
            exit 1
          fi
  tag-release:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - run: |
          cd nextjs-docker
          npm install
          npx semantic-release
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Tear down
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "cd CD-example-app/ && docker compose down"
      - run:
          name: Pull changes and rebuild
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "cd CD-example-app/ && git pull && docker compose up --build -d"
      # - discord/status:
      #     success_message: ":tada: A production deployment of ${CIRCLE_TAG} has occured."
      #     failure_message: "PRODUCTION DEPLOYMENT FAILED"

workflows:
  deploy-workflow:
    jobs:
      - check-branch:
          filters:
            branches:
              only:
                - main
      - tag-release: 
          requires:
            - check-branch
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
