version: 2.1

jobs:
  check-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          if [ $(git rev-parse HEAD) == $(git rev-parse staging) ]; then
            echo "SUCCESS: deploy conditions met"
            exit 0
          else
            echo "ERROR: You can only deploy when main and staging point to the same commit."
            exit 1
          fi


workflows:
  deploy-workflow:
    jobs:
      - check-branch:
          filters:
            branches:
              only:
                - main
