version: 2.1

jobs:
  check-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git clone -b staging "$CIRCLE_REPOSITORY_URL" .
      - run: |
          if [ << pipeline.git.revision >> == $(git rev-parse HEAD) ]; then
            echo "SUCCESS: deploy conditions met"
            exit 0
          else
            echo "ERROR: You can only deploy when main and staging point to the same commit."
            exit 1
          fi


workflows:
  deploy-workflow:
    jobs:
      - check-branch:
          filters:
            branches:
              only:
                - main
