version: '3.8'

# contrived cluster in a docker container stack

services:

##################################################################################
## Cluster PEER 1 ################################################################
##################################################################################

  ipfs1:
    container_name: ipfs1
    build: ./gateway
    env_file: .env
    ports:     
    # Swarm listens on all interfaces, so is remotely reachable.
      - "4001:4001/tcp"
      - "4001:4001/udp"
      # note: do not expose 5001 to the internet
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
      - "8081:8080"
    volumes:
      - ${IPFS_CLUSTER_DATADIR}/ipfs-cluster/ipfs1:/data/ipfs

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
          # Open API port (allows ipfs-cluster-ctl usage on host)
          - "127.0.0.1:9094:9094"
          # The cluster swarm port would need  to be exposed if this container
          # was to connect to cluster peers on other hosts.
          # But this is just a testing cluster.
          # - "9095:9095" # Cluster IPFS Proxy endpoint
          # - "9096:9096" # Cluster swarm endpoint
          # - "9097:9097/tcp" # Cluster pinning service enpoint
    volumes:
      - ${IPFS_CLUSTER_DATADIR}/ipfs-cluster/cluster1:/data/ipfs-cluster

##################################################################################
## Cluster PEER 2 ################################################################
##################################################################################

  ipfs2:
    container_name: ipfs2
    build: ./gateway
    env_file: .env
    ports:     
      - "8082:8080"
    volumes:
      - ${IPFS_CLUSTER_DATADIR}/ipfs-cluster/ipfs2:/data/ipfs

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ${IPFS_CLUSTER_DATADIR}/ipfs-cluster/cluster2:/data/ipfs-cluster

##################################################################################
## Cluster PEER 3 ################################################################
##################################################################################

  ipfs3:
    container_name: ipfs3
    build: ./gateway
    env_file: .env
    ports:     
      - "8083:8080"
    volumes:
      - ${IPFS_CLUSTER_DATADIR}/ipfs-cluster/ipfs3:/data/ipfs

  cluster3:
    container_name: cluster3
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs3
    environment:
      CLUSTER_PEERNAME: cluster3
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs3/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ${IPFS_CLUSTER_DATADIR}/ipfs-cluster/cluster3:/data/ipfs-cluster
