name: 'Check Branch'

on:
  push:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set env
        run: export STAGING_SHA=$(git rev-parse staging) && \
          export MAIN_SHA=$(git rev-parse HEAD)
      - name: Check branch
        if: ${{ env.MAIN_SHA != env.STAGING_SHA }}
        run: |
          echo "ERROR: You can only merge to main from staging."
          exit 1