name: 'Check Branch'

on:
  push:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - name: Set env
        run: echo "STAGING_SHA=$(git rev-parse staging)" >> $GITHUB_ENV 
      - name: Check branch
        if: ${{ github.sha != env.STAGING_SHA }}
        run: |
          if [[ ${{ github.sha }} == ${{ env.STAGING_SHA }} ]]; then
            exit 0
          else
            echo "ERROR: You can only merge to main from staging."
            exit 1
          fi