name: 'Check Branch'

on:
  push:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "STAGING_SHA=$(git rev-parse staging)" >> $GITHUB_ENV && \
          echo "MAIN_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Check branch
        if: ${{ env.MAIN_SHA != env.STAGING_SHA }}
        run: |
          echo "ERROR: You can only merge to main from staging."
          exit 1